/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32401xx.h"

#include "UART_Zero_copy.h"
#include <stdint.h>
#include <string.h>


//#define MAX_tokens  0x08

uint8_t Tx_Buff[128] = "LED_ON_1000\n";    // 1st command

uint8_t Len;

GPIO_Handle_t  GPIO_UART;
UART_Handle_t  UART2_Config;

void GPIO_UART2_AFMODE()
{
	GPIO_PeriClockControl(GPIOA, ENABLE);

	GPIO_UART.pGPIOx = GPIOA;
	GPIO_UART.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_ALTFUN;
	GPIO_UART.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_2;   // TX PIN
	GPIO_UART.GPIO_PinConfig.GPIO_PinAltFunMode = GPIO_AF7;
	GPIO_UART.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;
	GPIO_UART.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_MEDIUM;
	GPIO_UART.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;

	GPIO_Init(&GPIO_UART);   // TX INIT PA -2


	// PA3 - USART2_RX
	GPIO_UART.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_3;   // RX PIN
	GPIO_Init(&GPIO_UART);   //RX INIT PA -3


}




void UART_CONFIG()
{
	UART_periClockControl(UART2, ENABLE);

	UART2_Config.pUARTx = UART2;
	UART2_Config.UART_Config.BaudRate = 9600;
	UART2_Config.UART_Config.UART_Mode = UART_MODE_TXRX;
	UART2_Config.UART_Config.UART_Parity_Control = UART_PARITY_DISABLE;
	UART2_Config.UART_Config.UART_HWFlowControl = UART_HW_FLOW_CTRL_NONE;
	UART2_Config.UART_Config.WordLength = UART_WORDLEN_8BITS;
	UART2_Config.UART_Config.UART_STOP = UART_STOPBIT_1;

	UART_Init(&UART2_Config);


}




#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	GPIO_UART2_AFMODE();     // config  PA-2,3 as uart pin

	UART_CONFIG();      // init uart pins

	UART_periPheralControl(UART2, ENABLE);    // enable clock for uart

	Len = strlen((char *)(Tx_Buff));     // len of txbuff = 10
	UART_SendDataIT(&UART2_Config, Tx_Buff, Len);   // sending 1st command LED_ON_1000\n

}




