
#ifndef INC_STM32401XXGPIO_H_
#define INC_STM32401XXGPIO_H_

#include <stdint.h>
#include "../../Drivers/Inc/stm32401xx.h"

/* PIN CONFIG STRUCT
 * a pin can config in mode - input /putput/alternate fun / analog
 * if output mode means - open drain or push-pull
 * if input mode means does it need pull-up , pull-down reg
 * speed of the pin - fast or slow ,medium ( transction from one voltage high to low or low - high
 */
typedef struct
{
	uint8_t  GPIO_PinNumber;
	uint8_t  GPIO_PinMode;    /* Possible values at  @GPIO_PIN_MODES */
	uint8_t  GPIO_PinSpeed;    /* Possible values at  @GPIO_PIN_SPEED */
	uint8_t  GPIO_PinPuPdControl;  /* Possible values at  @GPIO_PUPD_MODES */
	uint8_t  GPIO_PinOPType;     /* Possible values at  @GPIO_OUTPUT_TYPES */
	uint8_t  GPIO_PinAltFunMode;  /*Possiblie values at @GPIO_AF_MODES */

}GPIO_PinConfig_t;



/*
 * 1.this is a handle structure for GPIO PIN
 */

typedef struct
{
	// pointer to hold base address of any gpio peripheral
	GPIO_RegDef_t      *pGPIOx ; /* this pointer hold gpio ba*/
	GPIO_PinConfig_t    GPIO_PinConfig; /* this pin holds gpio pin config settings */

}GPIO_Handle_t;







/*
 * @GPIO_PIN_MODES
 *  MACROS START HERE FOR GPIO MODE
 */
#define GPIO_PIN_NO_0        0
#define GPIO_PIN_NO_1        1
#define GPIO_PIN_NO_2        2
#define GPIO_PIN_NO_3        3
#define GPIO_PIN_NO_4        4
#define GPIO_PIN_NO_5        5
#define GPIO_PIN_NO_6        6
#define GPIO_PIN_NO_7        7
#define GPIO_PIN_NO_8        8
#define GPIO_PIN_NO_9        9
#define GPIO_PIN_NO_10       10
#define GPIO_PIN_NO_11       11
#define GPIO_PIN_NO_12       12
#define GPIO_PIN_NO_13       13
#define GPIO_PIN_NO_14       14
#define GPIO_PIN_NO_15       15



/*
 * @GPIO_PIN_MODES
 *   HERE FOR GPIO MODES
 */

#define GPIO_MODE_IN         0
#define GPIO_MODE_OUT        1
#define GPIO_MODE_ALTFUN     2
#define GPIO_MODE_ANALOG     3
#define GPIO_MODE_IT_FT      4
#define GPIO_MODE_IT_RT      5
#define GPIO_MODE_IT_RFT     6

/*
 *   @GPIO_OUTPUT_TYPES
 *  GPIO PIN possible output types
 */

#define GPIO_OP_TYPE_PP  0
#define GPIO_OP_TYPE_OD  1

/*
 * @GPIO_PIN_SPEED
 *  GPIO PIN possible SPEED types
 */

#define GPIO_SPEED_LOW        0
#define GPIO_SPEED_MEDIUM     1
#define GPIO_SPEED_FAST       2
#define GPIO_SPEED_HIGH       3

/*
 * @GPIO_PUPD_MODES
 *  GPIO PIN possible PULL-UP & PULL-DOWN Config
 */
#define GPIO_NO_PUPD          0
#define GPIO_PU               1
#define GPIO_PD               2


#define GPIO_PIN_SET       1
#define GPIO_PIN_RESET     0

/*
 * @GPIO_AF_MODES
 * GPIO Alternate Function Modes
 *
 */

#define GPIO_AF0    0
#define GPIO_AF1    1
#define GPIO_AF2    2
#define GPIO_AF3    3
#define GPIO_AF4    4
#define GPIO_AF5    5
#define GPIO_AF6    6
#define GPIO_AF7    7
#define GPIO_AF8    8
#define GPIO_AF9    9
#define GPIO_AF10   10
#define GPIO_AF11   11
#define GPIO_AF12   12
#define GPIO_AF13   13
#define GPIO_AF14   14
#define GPIO_AF15   15




/******************************************************************************************************
 *                  3.APIs supported by this driver
 *                  For more info about api check fun defin
 *
 **************************************************************************************************/


/* peripheral clock setup */
void GPIO_PeriClockControl(GPIO_RegDef_t *pGPIOx,uint8_t EnorDi);


/* GPIO INIT & DEINT */

void GPIO_Init(GPIO_Handle_t *pGPIOHandle );
void GPIO_DeInit(GPIO_RegDef_t *pGPIOx );

//write pin
void GPIO_WriteToOutputPin(GPIO_RegDef_t *pGPIOx,uint8_t PinNumber,uint8_t Value);
void GPIO_WriteToOutputPort(GPIO_RegDef_t *pGPIOx,uint16_t Value);


//read pin
uint8_t GPIO_ReadFromInputPin(GPIO_RegDef_t *pGPIOx,uint8_t PinNumber);
void GPIO_READToOutputPort(GPIO_RegDef_t *pGPIOx,uint16_t Value);


//toggle
void GPIO_ToggleToOutputPin(GPIO_RegDef_t *pGPIOx,uint8_t PinNumber);

/*interrupt */

/* To config interrupt generated by the pin
 * steps - gpio port issue interrupt to exti lines 0 - 15 so
 * enable interrput in nvic based on irq num assigned by designers
 * if nvic iser reg enable particular bit it is non masked and serve interrput by cpu
 * since we have shared exti lines in nvic its mandatory to check pr reg when entered into irq handler nd clear that bit
 */

void GPIO_IRQInterruptConfig(uint8_t IRQnumber,uint8_t EnorDi);

#endif /* INC_STM32401XXGPIO_H_ */
